language: python
python:
  - "3.9"

dist: focal  # Use Ubuntu 20.04 (which has SQLite 3.31.1 by default)

# Install Python dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt

# Apply migrations and run tests
script:
  - python manage.py migrate
  - pytest

# Deployment to Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"  # Your AWS region
  app: "polls"  # Your Elastic Beanstalk app name
  env: "polls-dev"  # Your Elastic Beanstalk environment name
  bucket_name: "elasticbeanstalk-us-east-1-009160062836"  # Replace with the actual S3 bucket name
  on:
    branch: master  # Deploy only on the master branch
