language: python
python:
  - "3.9"  # Specify your Python version

# Install SQLite from source and use it
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsqlite3-dev wget  # Install necessary libraries
  - wget https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz  # Download SQLite source code
  - tar xzf sqlite-autoconf-3330000.tar.gz
  - cd sqlite-autoconf-3330000
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - cd ..
  - sqlite3 --version  # Check if the new version is installed correctly

# Ensure the new SQLite is recognized
before_script:
  - export LD_LIBRARY_PATH="/usr/local/lib"  # Ensure correct linking
  - export PATH="/usr/local/bin:$PATH"  # Ensure the correct SQLite version is used
  - sqlite3 --version  # Verify that the correct version is in use

# Install Python dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt

# Apply migrations and run tests
script:
  - python manage.py migrate  # Apply migrations
  - pytest  # Run tests
