language: python
python:
  - "3.9"

# Install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sqlite3 libsqlite3-dev  # Install the latest version of SQLite
  - sqlite3 --version  # Check the installed version to ensure it meets Django's requirements

# Install Python dependencies
install:
  - pip install -U pip
  - pip install -r requirements.txt

# Run migrations and tests
before_script:
  - python manage.py migrate  # Apply migrations for testing

script:
  - pytest  # Run tests using pytest

# Cache pip for faster subsequent builds
cache:
  pip: true
